### ISSUE TITLE
Files index.md are ignored by TocDocFxCreation

### ISSUE THREAD

**Issue by sacrejohn** [Ellerbach/docfx-companion-tools#1]
Hello, 

I don't understand why the `index.md` files are ignored by **TocDocFxCreation** and don't appear in the toc file ?

Regards, 

Jonathan

**Comment by Ellerbach** [comment]
Hi, can you give a bit more context? 
`index.md` files are definitively used. There is even an option to create them if they are not present.

**Comment by sacrejohn** [comment]
Example :

I have a directory containing 3 files :
- index.md
- file1.md
- file2.md

I execute **TocDocFxCreation** in this directory : 

`TocDocFxCreation.exe -d test`

Desired file :

```yml
# This is an automatically generated file
items:
- name: Index
  href: index.md
- name: File1
  href: file1.md
- name: File2
  href: file2.md
```
Resulting file :

```yml
# This is an automatically generated file
items:
- name: File1
  href: file1.md
- name: File2
  href: file2.md
```

[test.zip](https://github.com/Ellerbach/docfx-companion-tools/files/6893455/test.zip)
