### ISSUE TITLE
TocGenerator doesn't link to generated index.md the first run, and contains index while parent item links to it

### ISSUE THREAD

**Issue by CodeCasterNL** [Ellerbach/docfx-companion-tools#27]
Given this directory structure:

* A
  * B.md
* index.md

Running `DocFxTocGenerator.exe --docfolder DocFxIndex  --index`, the toc.yml contains:

```yaml
items:
- name: DocFxIndex
  href: index.md
- name: A
  href: A/B.md # Links to B.md instead of index.md
  items:
  - name: A
    href: A/index.md
  - name: B
    href: A/B.md
```

## Issue 1:
The root-level item "A" links to `A/B.md`, because at generation-time the `A/index.md` didn't exist yet. 

Running the TOC generator a second time fixes that:

```yaml
items:
- name: DocFxIndex
  href: index.md
- name: A
  href: A/index.md # now links to A/index.md
  items:
  - name: A
    href: A/index.md # there's A/index.md again!
  - name: B
    href: A/B.md
```

## Issue 2:
Now the TOC contains "A/index.md" twice, resulting in weird nesting in the menu, mentioning "A" twice:

![A-A](https://user-images.githubusercontent.com/1726333/230732365-3b785a16-0570-41c1-8050-7f584a57c123.png)

## Expectations
I would expect:
* The index.md generation to be done depth-first, so the index.md can be added as the directory link instead of the next first file found (in other words, that the TOC generation with `--index` is stable).
* An item with children that links to an index.md not to contain the index.md as item again.

So:

```yaml
items:
- name: DocFxIndex
  href: index.md
- name: A
  href: A/index.md
  items:
  - name: B
    href: A/B.md
```

![A-B](https://user-images.githubusercontent.com/1726333/230732544-3c0b35ee-87ed-4d3b-bdc7-9351388d5513.png)
