### ISSUE TITLE
TocGenerator creates pointless/duplicate table items.

### ISSUE THREAD

**Issue by alanSherba** [Ellerbach/docfx-companion-tools#52]
When generating toc's with the following params:
```
 -s -r -m 1 -g -v -i
 ```
 The TOC's that get generated will contain duplicate entries for a folders `index.md`
 
 With the following folder structure:
 ```
 > docs
     - index.md
     > manual
          - index.md
          > folderA
              - index.md
              - example1.md
              - example2.md
          > folderB
              - index.md
              - example.md
 ```
 
 I get the following `toc.yml` in the `manual` folder:
 ```yml
items:
- name: Manual
  href: index.md
- name: FolderA
  href: FolderA/index.md
  items:
  - name: FolderA                <------ POINTLESS!
    href: FolderA/index.md       <------ POINTLESS!
  - name: Example 1
    href: FolderA/example1.md
  - name: Example 2
    href: FolderA/example2.md
- name: FolderB
  href: FolderB/index.md
  items:
  - name: FolderB
    href: FolderB/index.md
  - name: Example
    href: FolderB/example.md
```

When I build this the problem becomes more obvious. Index files are essentially listed twice. Once as the "foldout" then again as an item inside the foldout:
![image](https://github.com/Ellerbach/docfx-companion-tools/assets/100000804/57134a7c-cebf-4385-ac04-83b4f4eab3e1)

If I delete the duplicate items in the `toc.yml`'s and re-build it all works correctly:

![image](https://github.com/Ellerbach/docfx-companion-tools/assets/100000804/2ab28acd-838f-4669-9019-04fb71ab059b)

**Comment by Ellerbach** [comment]
if you remove the -i option, you should have the behavior you need if I remember correctly!

**Comment by mtirionMSFT** [comment]
@alanSherba you are right. Working on an improvement that should also fix #55.

**Comment by alasdair-at-flasher** [comment]
I still see this behaviour with `-g -r -s -v`

I also tried renaming all my index.md files to overview.md and got instead:
```
items:
- name: Features
  href: features/overview.md
  items:
  - name: Features
    href: features/overview.md
  - name: Custom site settings
    href: features/custom-site-settings/default-render-controller.md
    items:
    - name: Default Render Controller
      href: features/custom-site-settings/default-render-controller.md
    - name: Overview
      href: features/custom-site-settings/overview.md
```
      
 from this tree:
```
 ─features
│   │   │   .ignore
│   │   │   .order
│   │   │   overview.md
│   │   │
│   │   ├───custom-site-settings
│   │   │       default-render-controller.md
│   │   │       overview.md
```
Let me know if I can help :)
